# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # increment_build_number(xcodeproj: "fc-poc-wf.xcodeproj")

    build_app(
      workspace: "fc-poc-wf.xcworkspace",
      scheme: "Moxito",
      # clean: true  # Clean the build directory
    )

    scan(
      scheme: "Moxito",
      workspace: "fc-poc-wf.xcworkspace", # or YourApp.xcodeproj
      devices: ["iPhone 14"],           # You can change the device here
      # clean: true,
      build_for_testing: true
    )

    api_key = app_store_connect_api_key(
      key_id: "B25S2J8AHV",
      issuer_id: "8033b357-2d4f-4b7b-b056-967c4ba4b154",
      key_filepath: "./AuthKey_B25S2J8AHV.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(api_key: api_key)
  end
end
