name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-15
    environment: 'PRODUCTION'

    steps:
    - uses: actions/checkout@v4
    
    - name: List Available Xcode Versions
      run: ls -la /Applications/Xcode*
    
    - name: Select Xcode Version
      run: |
        XCODE_PATH=$(ls -d /Applications/Xcode*.app | sort -V | tail -n 1)
        echo "Using Xcode at: $XCODE_PATH"
        sudo xcode-select -s "$XCODE_PATH"
    
    - name: Generate Config Files
      run: |
        cat > Config-Release.xcconfig << EOF
        NEYNAR_API_KEY = ${{ secrets.NEYNAR_API_KEY }}
        EOF
    - name: Install Dependencies
      run: |
        brew install swiftlint
        brew install getsentry/tools/sentry-cli

    - name: Cache SPM
      uses: actions/cache@v3
      with:
        path: |
          ~/.build
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Cache Derived Data
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/*.xcodeproj/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-  
    
    - name: Build
      timeout-minutes: 10
      run: |
        xcodebuild build-for-testing \
          -workspace fc-poc-wf.xcworkspace \
          -scheme "Moxito" \
          -configuration Debug \
          -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16' \
          COMPILER_INDEX_STORE_ENABLE=NO \
          | xcpretty --color --simple

    - name: Test
      timeout-minutes: 10
      run: |
        xcodebuild test-without-building \
          -workspace fc-poc-wf.xcworkspace \
          -scheme "Moxito" \
          -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16' \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults \
          | xcpretty --color --simple
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        xcode: true
        xcode_derived_data: ~/Library/Developer/Xcode/DerivedData