name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    
    - name: List Available Xcode Versions
      run: ls -la /Applications/Xcode*
    
    - name: Select Xcode Version
      run: |
        XCODE_PATH=$(ls -d /Applications/Xcode*.app | sort -V | tail -n 1)
        echo "Using Xcode at: $XCODE_PATH"
        sudo xcode-select -s "$XCODE_PATH"
    
    - name: Generate Config Files
      run: |
        cat > Config-Release.xcconfig << EOF
        NEYNAR_API_KEY = NEYNAR_DOCS
        EOF

    - name: Install Dependencies
      run: |
        brew install swiftlint
        brew install getsentry/tools/sentry-cli 
    
    - name: Prepare for Testing
      run: |
        echo "Killing existing simulator processes..."
        killall Simulator || true
        killall -9 com.apple.CoreSimulator.CoreSimulatorService || true
        
        echo "Getting specific simulator ID..."
        DEVICE_ID=$(xcrun simctl list devices | grep -m 1 'iPhone 16' | awk -F'[()]' '{print $2}')
        echo "Device ID: $DEVICE_ID"
        
        echo "Booting specific simulator..."
        xcrun simctl boot "$DEVICE_ID" || true
        sleep 10

    - name: Build
      timeout-minutes: 10
      run: |
        xcodebuild clean build-for-testing \
          -workspace fc-poc-wf.xcworkspace \
          -scheme "Moxito" \
          -configuration Debug \
          -destination "id=$DEVICE_ID" \
          | xcpretty --color --simple

    - name: Test
      timeout-minutes: 10
      run: |
        # Get specific simulator ID
        DEVICE_ID=$(xcrun simctl list devices | grep -m 1 'iPhone 16' | awk -F'[()]' '{print $2}')
        
        xcodebuild test-without-building \
          -workspace fc-poc-wf.xcworkspace \
          -scheme "Moxito" \
          -destination "id=$DEVICE_ID" \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults \
          -parallel-testing-enabled NO \
          -maximum-concurrent-test-simulator-destinations 1 \
          -disable-concurrent-destination-testing \
          | xcpretty --color --simple
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        xcode: true
        xcode_derived_data: ~/Library/Developer/Xcode/DerivedData